### ISSUE TITLE
Factory: validate factory content

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra-tests#89]
This could help to validate the data before sending them to the server.
We need also to have an option to remove the validation to send invalid objects for testing purposes.

Extra: investigate how we could use these classes to create a dynamic documentation of the input structures. This documentation is created currently manually and it has not been always up-to-date.

**Comment by jmorel** [comment]
After discussion with @samlesu, the need here is:
1. transform the *Spec classes from `factory.py` into pydantic-validated objects (similar to what is done for `assets.py`
2. make all `AssetsFactory.create_*` methods accept a new parameter, `validate` that defaults to True. Setting this parameter to false allows to pass invalid data to the spec that will be returned.

**Comment by jmorel** [comment]
I'm having an issue with the second bullet point. I'll take an example:
A DatasetSpec is defined as such: 
```python
class DatasetSpec(_Spec):
    name: str
    data_opener: str
    type: str
    description: str
    permissions: Permissions = None
    objective_key: str = None
```

And the factory method to create one is:
```python
    def create_dataset(self, objective=None, permissions=None):
```

Which means the factory method makes strong assumptions about the type of `objective` and `permissions` to then map it to the attributes `objective_key` and `permissions`. And if automatically generates acceptable values for all other properties.

Adding a `validate=False` argument to the function would break the argument to property mapping and the resulting spec would still have acceptable defaults everywhere else.

Since the objective was to be able to create invalid specs, I'm thinking that we could have a `CopyCatSpec` object and a `Factory.create_copycat_spec(spec, **kwargs)` method that would work as such:
* `CopyCatSpec` has a `dict()` method that returns a dict (just like pydantic.BaseModel)
* `create_copycat_spec` 
  1. creates a new CopyCatSpec object, 
  2. inspects the referenced spec object to find default property values, adds these default values to the CopyCatSpec object
  3. takes the kwargs and sets them as property and values onto the CopyCatSpec object

This doesn't feel like a proper solution yet, but what do you think of the general idea?

**Comment by samlesu** [comment]
Thanks @jmorel  for your feedback. As you said having a `validate=False` does not seem like a good idea. I had a brief look at the existing tests and it looks like this feature is not required now.

If it's required for a specific test we could build as you said a dedicated Spec. I think it could be done directly in the test and it don't have to be part of the factory.

One other solution could be to do modify the attributes manually (for instance):

```python
x = Factory.create_valid_spec()
x.field = "invalid-value"
```

If this feature is not required right now, I propose to skip it and to focus on the 1st part.

**Comment by jmorel** [comment]
I'm liking this `create_valid_spec` idea, it'd make very clear which "wrong" value we're injecting into the spec. But as you said, it's not required right now for the tests.

Since the related PR is merged, I'm closing the issue.
